{
 "title": "Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "AppRole API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "AppRole_request_count", "legendFormat": "{{method}} - {{route}}" }
   ]
  },
  {
   "title": "User API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "User_request_count", "legendFormat": "{{method}} - {{route}}" }
   ]
  },
  {
   "title": "Group API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "Group_request_count", "legendFormat": "{{method}} - {{route}}" }
   ]
  },
  {
   "title": "GroupUser API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "GroupUser_request_count", "legendFormat": "{{method}} - {{route}}" }
   ]
  },
  {
   "title": "GroupWaitingList API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "GroupWaitingList_request_count", "legendFormat": "{{method}} - {{route}}" }
   ]
  },
  {
   "title": "GroupRole API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "GroupRole_request_count", "legendFormat": "{{method}} - {{route}}" }
   ]
  },
  {
   "title": "Event API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "Event_request_count", "legendFormat": "{{method}} - {{route}}" }
   ]
  },
  {
   "title": "EventUser API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "EventUser_request_count", "legendFormat": "{{method}} - {{route}}" }
   ]
  },
  {
   "title": "EventWaitingList API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "EventWaitingList_request_count", "legendFormat": "{{method}} - {{route}}" }
   ]
  }
 ]
}